language: ruby
rvm:
- 1.8.7
before_script:
after_script:
script: rake spec
after_success:
  - git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng
  - .forge-releng/publish
branches:
  only:
  - master
env:
  matrix:
  - PUPPET_VERSION=2.6.9
  - PUPPET_VERSION=2.7.6
  - PUPPET_VERSION=2.7.13
  - PUPPET_VERSION=3.0.0
  - PUPPET_VERSION=3.1.0
  - PUPPET_VERSION=3.3.0
  global:
    - PUBLISHER_LOGIN=saz
    - secure: |- 
        KHycFEf0ALVjITczYG0pcfk912muQkbJiGzKa5yyC8C9ppDW+dTYgDQu8AO1KXFHzds
        NUASY2XNjrJNv27w7A2eMp88qU1ID1s8CWALph4fuxGcM/HoPw9q8sldJ9/sHGlY9Ye
        DEeIvgt9qkwKtG/kb7dN7la42nv5fffWE95OU=
notifications:
  email: false
gemfile: .gemfile
